// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package demo

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDemo = "demo"

// Demo mapped from table <demo>
type Demo struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	CharDemo    string         `gorm:"column:char_demo;not null;comment:编码" json:"char_demo"`        // 编码
	TextDemo    string         `gorm:"column:text_demo;comment:名称" json:"text_demo"`                 // 名称
	DateDemo    time.Time      `gorm:"column:date_demo" json:"date_demo"`
	TimeDemo    string         `gorm:"column:time_demo" json:"time_demo"`
	BooleanDemo bool           `gorm:"column:boolean_demo" json:"boolean_demo"`
	ByteaDemo   []uint8        `gorm:"column:bytea_demo" json:"bytea_demo"`
	JSONDemo    string         `gorm:"column:json_demo" json:"json_demo"`
	CreatedAt   time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Demo's table name
func (*Demo) TableName() string {
	return TableNameDemo
}
