server:
  port: 8080
  name: "kumquat"
  mode: "debug"
  read_timeout: 10      # 秒
  write_timeout: 10     # 秒
  idle_timeout: 120     # 秒（2分钟）
  shutdown_timeout: 5   # 秒

database:
  driver: "postgres"
  host: ""
  port: 0
  username: ""
  password: ""
  database: ""
  charset: "utf8"
  max_idle_conns: 10
  max_open_conns: 100

redis:
  mode: "single"           # single 或 cluster
  addrs:
    - ""
  # username: ""
  password: ""
  db: 0
  pool_size: 10

log:
  level: "info"
  filename: "logs/app.log"
  max_size: 100 # MB
  max_backups: 7
  max_age: 30 # days
  compress: true

