server:
  port: 8080
  name: "kumquat"
  mode: "debug"
  read-timeout: 10      # 秒
  write-timeout: 10     # 秒
  idle-timeout: 120     # 秒（2分钟）
  shutdown-timeout: 5   # 秒

database:
  driver: "postgres"
  host: ""
  port: 0
  username: ""
  password: ""
  database: ""
  charset: "utf8"
  max-idle-conns: 10
  max-open-conns: 100

redis:
  mode: "standalone"       # standalone 或 cluster
  addrs:
    - ""
  # username: ""
  password: ""
  db: 0
  pool-size: 10

segmentlock:
  segment-count: 64           # 分段数量，建议 2 的幂（16, 32, 64, 128, 256）

jwt:
  access-secret: ""
  access-expire: 30           # minutes
  refresh-secret: ""
  refresh-expire: 720         # hours

log:
  level: "info"
  filename: "logs/app.log"
  max-size: 100 # MB
  max-backups: 7
  max-age: 30 # days
  compress: true
